### ISSUE TITLE
Swagger operation for path "api/v2/market/{name}" with "get" was not found

### ISSUE THREAD

**Issue by flost07** [adrenalinkin/swagger-resolver-bundle#15]
Hi, I faced an issue during the composer installation of your bundle.

It throws an exception with message: 
> Swagger operation for path "api/v1/market/{name}" with "get" was not found

By stepping through your code I noticed that the problem occurs when the mapping is generated.  
`private function initMapPathToRouteName(): void
    {
        foreach ($this->router->getRouteCollection() as $routeName => $route) {
            foreach ($route->getMethods() as $method) {
                $this->mapPathToRouteName[$route->getPath()][$method] = $routeName;
            }
        }
    }` 

`$method` will be passed as uppercase variant, e.g. "GET" - but the comparision if the mapping has been set will only check the lowercase variant, e.g. "get". 

I could solve the problem by adding the method always in the **lowercase** variant to the mapping. 

See:
`private function initMapPathToRouteName(): void
    {
        foreach ($this->router->getRouteCollection() as $routeName => $route) {
            foreach ($route->getMethods() as $method) {
                $this->mapPathToRouteName[$route->getPath()][strtolower($method)] = $routeName;
            }
        }
    }` 

I'm using FOS Rest and Nelmio, I've defined my routes with:

> @Rest\Get("api/v1/market/{name}/")

I don't know if its matters. 

Best regards;
Florian

**Comment by adrenalinkin** [comment]
@flost07 Hello!
Thanks you for report this issue.
Looks like a bug, furthermore I've never try to use this bundle in combination with FOS Rest. So this very possible situation when FOS Rest changed method to lowercase and here we are!

If you want become a contributor - you can create PR to fix this. If not - i will fix it by myself. Let me now about your decision.
