### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by derunterstrich** [adrenalinkin/swagger-resolver-bundle#80]
Hello,

Since PHP 7.4 is already EOL, I wanted to update my application to PHP 8.1. Unfortunately, it does not work because the compsoer "php" defaults to "^7.1". 

  Problem 1
    - Root composer.json requires adrenalinkin/swagger-resolver-bundle ^0.4.6 -> satisfiable by adrenalinkin/swagger-resolver-bundle[v0.4.6].
    - adrenalinkin/swagger-resolver-bundle v0.4.6 requires php ~7.1 -> your php version (8.1.13) does not satisfy that requirement.
   
Is an update planned here, or do I have to look for something new?

**Comment by mario-fehr** [comment]
> In present time I working on finishing coverage for this bundle. Аurther according to plan is improvements and fixes. And all of that will be a first stable release. First stable release should compatible with Symfony 3.4, so please don't try to remove compatibility in this issue

_Originally posted by @adrenalinkin in https://github.com/adrenalinkin/swagger-resolver-bundle/issues/72#issuecomment-1002195211_

**Comment by adrenalinkin** [comment]
Hello guys! this project already covered by tests but i was want to add more improvement before release first version of the package.

Anyway I think it would be better if you add support for php 8.1 I think we can start 2.0 branch where you can drop compatibilities with old version of php and symfony

And i reserve version 1.0 for old versions.

What are you thinking about this?

**Comment by mario-fehr** [comment]
@adrenalinkin sound good to me

**Comment by adrenalinkin** [comment]
@derunterstrich Hello! You can use 1.0.0 release to work with php 8

**Comment by derunterstrich** [comment]
big thx! it works fine!
